name: Pipeline Terraform AWS infraestrutura Kubernetes

on:
  push:
    branches:
      - '*'
      
jobs:

  terraform_plan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform Init
        run: terraform init

      - name: AWS Plan Copy
        id: copyfrom
        run: |
          if aws s3 ls s3://terraformestado/terraform.tfstate > /dev/null 2>&1
          then
            aws s3 cp s3://terraformestado/terraform.tfstate terraform.tfstate
          else
            echo "terraform.tfstate does not exist in the S3 bucket"
          fi

      - name: Terraform Plan
        id: plan
        run: terraform plan 

  deploy_infra:
    needs: terraform_plan
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve