name: Terraform CI/CD

on:
  push:
    branches:
      - master
      
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

  configure_aws:
    needs: checkout
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ secrets.AWS_REGION }}

  terraform_init:
    needs: configure_aws
    runs-on: ubuntu-latest
    steps:
      - name: Terraform Init
        run: terraform init

  aws_plan_copy:
    needs: terraform_init
    runs-on: ubuntu-latest
    steps:
      - name: AWS Plan Copy
        id: copyfrom
        run: |
          if aws s3 ls s3://terraformestado/terraform.tfstate > /dev/null 2>&1
          then
            aws s3 cp s3://terraformestado/terraform.tfstate terraform.tfstate
          else
            echo "terraform.tfstate does not exist in the S3 bucket"
          fi

  terraform_plan:
    needs: aws_plan_copy
    runs-on: ubuntu-latest
    steps:
      - name: Terraform Plan
        id: plan
        if: ${{ github.event_name == 'pull_request' || github.event_name == 'push' }} // Plan creation is required both on pull_request, push
        run: terraform plan 

  terraform_apply:
    needs: terraform_plan
    runs-on: ubuntu-latest
    steps:
      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve